name: ${project.artifactId}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
dev-url: ${project.url}
softdepend: [TagAPI]
commands:
    nff:
        description: root command for NoFriendlyFire
        usage: /nff - Show the main menu
    nff add:
        description: add a team
        usage: /nff add teamname color
    nff remove:
        description: remove a team
        usage: /nff remove teamname
    nff teams:
        description: list all teams with color
        usage: /nff teams
permissions:
    nofriendlyfire.admin:
        description: gives access to commands like reload
        default: op
    #All the permissions for the teams are assigned dynamically from the config and default to none.
    #for example: nofriendlyfire.teamname, nofriendlyfire.attackers